language: python
matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.4
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.8-dev
          dist: xenial
          sudo: true
        - python: pypy
          dist: trusty
          sudo: false
        - python: pypy3
          dist: trusty
          sudo: false
    allow_failures:
        - python: 3.8-dev
          dist: xenial
          sudo: true
script: tox
os:
  - linux
before_install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install requirements-builder
  - requirements-builder --level=min setup.py > .travis-lowest-requirements.txt
  - requirements-builder --level=pypi setup.py > .travis-release-requirements.txt
install:
  - pip install tox-travis
  - pip install coveralls
  - travis_retry pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install -e .
env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
after_success:
  # rcfile name duplicated in test/run.py
  - coveralls --rcfile="./test/.coverage_rc_mock_script"
