language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script: tox
os:
  - linux
install:
  - pip install tox-travis
  - pip install coveralls
env:
  global:
    - CI=true
after_success:
  - coveralls --rcfile="./test/.coverage_rc_mock"
