# Copyright © 2012 - 2024 Lars Hupfeldt Nielsen, Hupfeldt IT ApS

[build-system]
requires = ["setuptools >= 68.0.0", "wheel>=0.40.0", "setuptools_scm[toml]>=7.1.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
